// <auto-generated />
using Abitasharp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Abitasharp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180626181623_testSeed")]
    partial class testSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Abitasharp.Models.Annuncio", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CaratteristicheUtenteID");

                    b.Property<string>("IndirizzoPosizioneId");

                    b.Property<string>("Note");

                    b.Property<string>("UtenteRegolareID");

                    b.Property<string>("UtenteRegolareID1");

                    b.HasKey("ID");

                    b.HasIndex("CaratteristicheUtenteID");

                    b.HasIndex("IndirizzoPosizioneId");

                    b.HasIndex("UtenteRegolareID");

                    b.HasIndex("UtenteRegolareID1");

                    b.ToTable("Annunci");
                });

            modelBuilder.Entity("Abitasharp.Models.CaratteristicheUtente", b =>
                {
                    b.Property<string>("ID");

                    b.Property<bool?>("Animali");

                    b.Property<bool?>("Erasmus");

                    b.Property<bool?>("Famiglia");

                    b.Property<bool?>("Fumatore");

                    b.Property<bool?>("Genere");

                    b.Property<bool?>("Lavoratore");

                    b.Property<bool?>("Studente");

                    b.HasKey("ID");

                    b.ToTable("CaratteristicheUtente");
                });

            modelBuilder.Entity("Abitasharp.Models.Foto", b =>
                {
                    b.Property<string>("Path")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnnuncioID");

                    b.HasKey("Path");

                    b.HasIndex("AnnuncioID");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("Abitasharp.Models.Periodo", b =>
                {
                    b.Property<string>("PeriodoId");

                    b.Property<DateTime>("A");

                    b.Property<DateTime>("Da");

                    b.HasKey("PeriodoId");

                    b.ToTable("Periodo");
                });

            modelBuilder.Entity("Abitasharp.Models.Posizione", b =>
                {
                    b.Property<string>("PosizioneId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Indirizzo");

                    b.Property<float>("Lat");

                    b.Property<float>("Long");

                    b.HasKey("PosizioneId");

                    b.ToTable("Posizioni");
                });

            modelBuilder.Entity("Abitasharp.Models.Prezzo", b =>
                {
                    b.Property<string>("PrezzoId");

                    b.Property<int>("TipoPagamento");

                    b.Property<double>("Valore");

                    b.HasKey("PrezzoId");

                    b.ToTable("Prezzo");
                });

            modelBuilder.Entity("Abitasharp.Models.Recapiti", b =>
                {
                    b.Property<string>("RecapitiId");

                    b.Property<string>("Email1");

                    b.Property<string>("Email2");

                    b.Property<string>("Email3");

                    b.Property<string>("Tel1");

                    b.Property<string>("Tel2");

                    b.Property<string>("Tel3");

                    b.HasKey("RecapitiId");

                    b.ToTable("Recapiti");
                });

            modelBuilder.Entity("Abitasharp.Models.Ruolo", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Ruoli");
                });

            modelBuilder.Entity("Abitasharp.Models.RuoloUtente", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RuoloID");

                    b.Property<string>("UtenteID");

                    b.HasKey("ID");

                    b.HasIndex("RuoloID");

                    b.HasIndex("UtenteID");

                    b.ToTable("RuoliUtente");
                });

            modelBuilder.Entity("Abitasharp.Models.Segnalazione", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnnuncioID");

                    b.Property<string>("Messaggio");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UtenteRegolareID");

                    b.HasKey("ID");

                    b.HasIndex("AnnuncioID");

                    b.HasIndex("UtenteRegolareID");

                    b.ToTable("Segnalazioni");
                });

            modelBuilder.Entity("Abitasharp.Models.TipologiaAnnunci", b =>
                {
                    b.Property<string>("TipologiaAnnunciId");

                    b.Property<int>("TipoAnnuncio");

                    b.Property<int>("TipoContratto");

                    b.HasKey("TipologiaAnnunciId");

                    b.ToTable("TipologieAnnunci");
                });

            modelBuilder.Entity("Abitasharp.Models.Utente", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("PasswordHash");

                    b.HasKey("ID");

                    b.ToTable("Utenti");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Utente");
                });

            modelBuilder.Entity("Abitasharp.Models.Admin", b =>
                {
                    b.HasBaseType("Abitasharp.Models.Utente");


                    b.ToTable("Admin");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Abitasharp.Models.UtenteRegolare", b =>
                {
                    b.HasBaseType("Abitasharp.Models.Utente");


                    b.ToTable("UtenteRegolare");

                    b.HasDiscriminator().HasValue("UtenteRegolare");
                });

            modelBuilder.Entity("Abitasharp.Models.ProfiloAzienda", b =>
                {
                    b.HasBaseType("Abitasharp.Models.UtenteRegolare");

                    b.Property<string>("NomeAzienda");

                    b.Property<string>("PartitaIVa");

                    b.ToTable("ProfiloAzienda");

                    b.HasDiscriminator().HasValue("ProfiloAzienda");
                });

            modelBuilder.Entity("Abitasharp.Models.ProfiloPrivato", b =>
                {
                    b.HasBaseType("Abitasharp.Models.UtenteRegolare");

                    b.Property<string>("Cognome");

                    b.Property<DateTime>("DataNascita");

                    b.Property<string>("Nome");

                    b.ToTable("ProfiloPrivato");

                    b.HasDiscriminator().HasValue("ProfiloPrivato");
                });

            modelBuilder.Entity("Abitasharp.Models.Annuncio", b =>
                {
                    b.HasOne("Abitasharp.Models.CaratteristicheUtente", "CaratteristicheUtente")
                        .WithMany()
                        .HasForeignKey("CaratteristicheUtenteID");

                    b.HasOne("Abitasharp.Models.Posizione", "Indirizzo")
                        .WithMany()
                        .HasForeignKey("IndirizzoPosizioneId");

                    b.HasOne("Abitasharp.Models.UtenteRegolare")
                        .WithMany("ListaAnnunci")
                        .HasForeignKey("UtenteRegolareID");

                    b.HasOne("Abitasharp.Models.UtenteRegolare")
                        .WithMany("ListaPreferiti")
                        .HasForeignKey("UtenteRegolareID1");
                });

            modelBuilder.Entity("Abitasharp.Models.CaratteristicheUtente", b =>
                {
                    b.HasOne("Abitasharp.Models.ProfiloPrivato", "ProfiloPrivato")
                        .WithOne("CaratteristicheUtente")
                        .HasForeignKey("Abitasharp.Models.CaratteristicheUtente", "ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Abitasharp.Models.Foto", b =>
                {
                    b.HasOne("Abitasharp.Models.Annuncio")
                        .WithMany("Foto")
                        .HasForeignKey("AnnuncioID");
                });

            modelBuilder.Entity("Abitasharp.Models.Periodo", b =>
                {
                    b.HasOne("Abitasharp.Models.Annuncio", "Annuncio")
                        .WithOne("Periodo")
                        .HasForeignKey("Abitasharp.Models.Periodo", "PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Abitasharp.Models.Prezzo", b =>
                {
                    b.HasOne("Abitasharp.Models.Annuncio", "Annuncio")
                        .WithOne("Prezzo")
                        .HasForeignKey("Abitasharp.Models.Prezzo", "PrezzoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Abitasharp.Models.Recapiti", b =>
                {
                    b.HasOne("Abitasharp.Models.UtenteRegolare", "UtenteRegolare")
                        .WithOne("Recapiti")
                        .HasForeignKey("Abitasharp.Models.Recapiti", "RecapitiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Abitasharp.Models.RuoloUtente", b =>
                {
                    b.HasOne("Abitasharp.Models.Ruolo", "Ruolo")
                        .WithMany("RuoloUtente")
                        .HasForeignKey("RuoloID");

                    b.HasOne("Abitasharp.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteID");
                });

            modelBuilder.Entity("Abitasharp.Models.Segnalazione", b =>
                {
                    b.HasOne("Abitasharp.Models.Annuncio", "Annuncio")
                        .WithMany()
                        .HasForeignKey("AnnuncioID");

                    b.HasOne("Abitasharp.Models.UtenteRegolare")
                        .WithMany("ListaSegnalazioni")
                        .HasForeignKey("UtenteRegolareID");
                });

            modelBuilder.Entity("Abitasharp.Models.TipologiaAnnunci", b =>
                {
                    b.HasOne("Abitasharp.Models.Annuncio", "Annuncio")
                        .WithOne("Tipologia")
                        .HasForeignKey("Abitasharp.Models.TipologiaAnnunci", "TipologiaAnnunciId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
